#!/bin/sh


start() {
    echo "Loading modules "
    modprobe 8192cu
}

stop() {
    true
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
