#!/bin/sh

# Sanity checks
test -f /usr/bin/squeezelite || exit 0

start() {
	printf "Starting squeezelite: "
	start-stop-daemon --start --quiet --background --exec /usr/bin/squeezelite \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping squeezelite: "
	start-stop-daemon --stop --quiet --pidfile /var/run/squeezelite.pid \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
