#!/bin/sh

#/etc/init.d/checkstatus >> /dev/null 2>&1 &
# Screen Blanking abschalten
echo -e "\033[9;0]"

LD_LIBRARY_PATH=/lib
export LD_LIBRARY_PATH
TZ="Europe/Berlin"
export TZ

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
depmod -ae

mount -o ro /dev/mmcblk0p1 /mnt/mmcblk0p1 
echo "System:      We are aroio Version $(cat /mnt/mmcblk0p1/version)!"
/etc/init.d/modules &
/etc/init.d/gpio &
/etc/init.d/checkstatus &> /dev/null &

/etc/init.d/checkuserconfig
/etc/init.d/checksoundcard

mount none -t tmpfs -o defaults /var
mount none -t tmpfs -o defaults /tmp
mount none -t tmpfs -o defaults /opt
mount none -t tmpfs -o defaults /home/sftparoio

mkdir /dev/shm
mount none -t tmpfs -o defaults /dev/shm

mkdir -p /var/run/dbus

export LANG=en_US.utf8
/etc/init.d/lms extract &

cp -a /root/www /opt

mkdir /var/log

/etc/init.d/checklms &
/etc/init.d/amixer &
echo "System:      Copying default filters..."
cp -ar /mnt/mmcblk0p1/brutefir/*.dbl /home/sftparoio
tar xf /mnt/mmcblk0p1/filter.tgz -C /home/sftparoio && mv /home/sftparoio/filter/* /home/sftparoio && rmdir /home/sftparoio/filter
chown -R sftparoio /home/sftparoio
/etc/init.d/brutefir &

/etc/init.d/checkfilters &
/etc/init.d/network &
touch /var/log/shairportlog.txt
sleep 5
/usr/bin/startstreamer.sh &
/etc/init.d/httpd
loadkmap < /etc/de.map
chmod 777 /dev/null && dropbear
/etc/init.d/logrotate &> /dev/null &
/etc/init.d/ntpd &> /dev/null &

exit 0
