#!/bin/sh


# Script to stop all mode dependend init scripts

# Source our userconfig

CONFIG=/mnt/mmcblk0p1/userconfig.txt

if [ -e ${CONFIG} ];
then
    . ${CONFIG}
else
    echo "No userconfig, using defaults"
    . /etc/userconfig_default.txt
fi

# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     # Source shell script to pass user config
     (
	 trap - INT QUIT TSTP
	 set start
	 . $i
     )
done
