#!/bin/sh


# Script to stop all mode dependend init scripts

# Source our userconfig

CONFIG=/mnt/mmcblk0p1/userconfig.txt

if [ -e ${CONFIG} ];
then
    . ${CONFIG}
else
    echo "No userconfig, using defaults"
    . /etc/userconfig_default.txt
fi

if [ -e ${MODEFILE} ];
then
    OLDMODE=$(cat ${MODEFILE})
else
    echo "Failed to stop mode"
    exit 0
fi

echo "Stopping mode: $OLDMODE"

# Stop all init scripts in /etc/init.d/M$MODE
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/M$OLDMODE/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     # Source shell script to pass user config
     (
	 trap - INT QUIT TSTP
	 set stop
	 . $i
     )
done
