#!/bin/sh

. /mnt/mmcblk0p1/userconfig.txt

case $VOLUME in
	"0 dB")
	amixer sset 'Digital' 207 &> /dev/null
	;;

	"-1 dB")
	amixer sset 'Digital' 205 &> /dev/null
	;;

	"-2 dB")
	amixer sset 'Digital' 203 &> /dev/null
	;;

	"-3 dB")
	amixer sset 'Digital' 201 &> /dev/null
	;;

	"-4 dB")
	amixer sset 'Digital' 199 &> /dev/null
	;;

	"-5 dB")
	amixer sset 'Digital' 197 &> /dev/null
	;;

	"-6 dB")
	amixer sset 'Digital' 195 &> /dev/null
	;;

	"-12 dB")
	amixer sset 'Digital' 183 &> /dev/null
	;;

esac

echo "Mixer:       Setting master output volume to $VOLUME."
