#!/bin/sh

## unklar, aber dabei
modprobe bcm2835-gpiomem
modprobe uio

## WIFI
  modprobe 8192cu

## AUDIO

#  modprobe bcm2708-dmaengine
  modprobe i2c-bcm2708
  modprobe snd-soc-bcm2708-i2s
#  modprobe snd-soc-pcm5102a
  modprobe snd-soc-pcm512x
  modprobe snd-soc-pcm512x-i2c

## Hier noch eine autom. Erkennung fuer den DAC einbauen...

  ## IQ-AUDIO-DAC
   modprobe snd-soc-iqaudio-dac

  ## HIFI-BERRY-DAC
#   modprobe snd-soc-wm8804
#   modprobe snd-soc-hifiberry-dacplus
#   modprobe snd-soc-hifiberry-digi

# Alsa loopback device
#  modprobe snd-aloop

## Sollte jemand eine NTFS-Festplatte haben...
  modprobe ntfs

## Bluetooth
#  modprobe btusb
