#!/bin/sh

. /etc/aroio/userconfig

NAME=audio
PIDFILE=/var/run/$NAME.pid

start_jack() {
    echo " BruteFIR enabled, starting with Jack"
    /etc/init.d/jackd start
    /etc/init.d/brutefir start
    case $AUDIOPLAYER in
	squeezelite)
	    /etc/init.d/squeezelite-jack start
	    /etc/init.d/shairport start
	    ;;
	gmediarender)
	    /etc/init.d/gmediarender start
	    /etc/init.d/shairport start
	    ;;
	netjack)
	    /etc/init.d/netjack start
	    ;;
    esac
}

start_nojack() {
    echo " BruteFIR disabled"
    case $AUDIOPLAYER in
	squeezelite)
	    /etc/init.d/squeezelite start
	    ;;
	gmediarender)
	    /etc/init.d/gmediarender start
	    ;;
    esac
    /etc/init.d/shairport start
}

start() {
    echo "Initializing audio subsystem"
    if [ x$BRUTEFIR = xON ]
    then
	start_jack
    else
	start_nojack
    fi
}

stop() {
    echo "Shutting down audio subsystem"
    /etc/init.d/brutefir stop
    /etc/init.d/shairport stop
    /etc/init.d/squeezelite-jack stop
    /etc/init.d/squeezelite stop
    /etc/init.d/gmediarender stop
    /etc/init.d/jackd stop
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
