#!/bin/sh

. /etc/aroio/userconfig

DAEMON_NAME=brutefir
DAEMON=/usr/bin/brutefir
PIDFILE=/var/run/$DAEMON_NAME.pid
DAEMON_ARGS="/root/brutefir_config"

prepare_config() {
    case $CHANNELS in
	2)
	    if [ "$MSCODING" = "ON"  ]
	    then	cp /root/brutefir_config.default.jack.mscoded /root/brutefir_config
	    else	cp /root/brutefir_config.default.jack.stereo /root/brutefir_config
	    fi
	    ;;

	4)
	    cp /root/brutefir_config.default.jack.4-channel /root/brutefir_config
	    ;;
    esac

    counter=-1
    case $CHANNELS in
	2)
	    for i in $(grep -o "COEFF_NAME[^m]" /mnt/mmcblk0p1/userconfig.txt)
	    do
		COEFF_NAME=$(eval "echo \$$i")
		counter=$((counter+1))
		if [ "$COEFF_NAME" = ""  ] ; then COEFF_NAME="BypassFilter" ; fi
		if ! [ -e /home/sftparoio/"$COEFF_NAME"L"$RATE".dbl ]  ; then COEFF_NAME="BypassFilter" ; fi
		sed -i -- s/"coeff\"left"$counter"\"{filename:\"\/home\/sftparoio\/BypassFilterL96.dbl\";"/"coeff\"left"$counter"\"{filename:\"\/home\/sftparoio\/"$COEFF_NAME"L"$RATE".dbl\";"/g /root/brutefir_config
		sed -i -- s/"coeff\"right"$counter"\"{filename:\"\/home\/sftparoio\/BypassFilterR96.dbl\";"/"coeff\"right"$counter"\"{filename:\"\/home\/sftparoio\/"$COEFF_NAME"R"$RATE".dbl\";"/g /root/brutefir_config
		sed -i -- s/"96000"/""$RATE"000"/g /root/brutefir_config
	    done
	    ;;
	4)
	    for i in $(grep -o "COEFF_NAME[^m]" /mnt/mmcblk0p1/userconfig.txt)
	    do
		COEFF_NAME=$(eval "echo \$$i")
		counter=$((counter+1))
		if [ "$COEFF_NAME" = ""  ] ; then COEFF_NAME="BypassFilter" ; fi
		if ! [ -e /home/sftparoio/"$COEFF_NAME"L"$RATE".dbl ]  ; then COEFF_NAME="BypassFilter" ; fi
		sed -i -- s/"coeff\"left"$counter"\"{filename:\"\/home\/sftparoio\/BypassFilterL96.dbl\";"/"coeff\"left"$counter"\"{filename:\"\/home\/sftparoio\/"$COEFF_NAME"L"$RATE".dbl\";"/g /root/brutefir_config
		sed -i -- s/"coeff\"right"$counter"\"{filename:\"\/home\/sftparoio\/BypassFilterR96.dbl\";"/"coeff\"right"$counter"\"{filename:\"\/home\/sftparoio\/"$COEFF_NAME"R"$RATE".dbl\";"/g /root/brutefir_config
		sed -i -- s/"coeff\"sleft"$counter"\"{filename:\"\/home\/sftparoio\/BypassFilterL96.dbl\";"/"coeff\"sleft"$counter"\"{filename:\"\/home\/sftparoio\/"$COEFF_NAME"SL"$RATE".dbl\";"/g /root/brutefir_config
		sed -i -- s/"coeff\"sright"$counter"\"{filename:\"\/home\/sftparoio\/BypassFilterR96.dbl\";"/"coeff\"sright"$counter"\"{filename:\"\/home\/sftparoio\/"$COEFF_NAME"SR"$RATE".dbl\";"/g /root/brutefir_config
		sed -i -- s/"96000"/""$RATE"000"/g /root/brutefir_config
	    done
	    ;;
    esac
    ##### BIS HIER SOLLTE MULTICHANNEL EINGEBUNDEN SEIN, AB HIER WEITERSCHREIBEN
    ##### BISHER SOLLTE STEREO WEITERLAUFEN WIE BISHER, TESTEN!!!!!

    ## paste together attenuation and phase for default coeff
    ATT="_ATT"
    COEFF="COEFF"
    DEF_COEFF_ATT='$COEFF$ATT$DEF_COEFF'
    eval DEF_COEFF_ATT=$DEF_COEFF_ATT
    DEF_COEFF_ATT=$(eval echo \$$DEF_COEFF_ATT)

    PHASE="_PHASE"
    COEFF="COEFF"
    DEF_COEFF_PHASE='$COEFF$PHASE$DEF_COEFF'
    eval DEF_COEFF_PHASE=$DEF_COEFF_PHASE
    DEF_COEFF_PHASE=$(eval echo \$$DEF_COEFF_PHASE)

    NAME="_NAME"
    COEFF="COEFF"
    DEF_COEFF_NAME='$COEFF$NAME$DEF_COEFF'
    eval DEF_COEFF_NAME=$DEF_COEFF_NAME
    DEF_COEFF_NAME=$(eval echo \$$DEF_COEFF_NAME)

    ATT="_ATT"
    SCOEFF="SCOEFF"
    DEF_SCOEFF_ATT='$SCOEFF$ATT$SDEF_COEFF'
    eval DEF_SCOEFF_ATT=$DEF_SCOEFF_ATT
    DEF_SCOEFF_ATT=$(eval echo \$$DEF_SCOEFF_ATT)

    PHASE="_PHASE"
    SCOEFF="SCOEFF"
    DEF_SCOEFF_PHASE='$SCOEFF$PHASE$SDEF_COEFF'
    eval DEF_SCOEFF_PHASE=$DEF_SCOEFF_PHASE
    DEF_SCOEFF_PHASE=$(eval echo \$$DEF_SCOEFF_PHASE)

    NAME="_NAME"
    SCOEFF="SCOEFF"
    DEF_SCOEFF_NAME='$SCOEFF$NAME$DEF_SCOEFF'
    eval DEF_SCOEFF_NAME=$DEF_SCOEFF_NAME
    DEF_SCOEFF_NAME=$(eval echo \$$DEF_SCOEFF_NAME)

    if [ "$DEF_COEFF" = "" ] ; then DEF_COEFF="0" ; fi
    if [ "$DEF_COEFF_PHASE" = "" ] ; then DEF_COEFF_PHASE="1" ; fi
    if [ "$DEF_COEFF_ATT" = "" ] ; then DEF_COEFF_ATT="0" ; fi

    if [ "$DEF_SCOEFF" = "" ] ; then DEF_COEFF="0" ; fi
    if [ "$DEF_SCOEFF_PHASE" = "" ] ; then DEF_COEFF_PHASE="1" ; fi
    if [ "$DEF_SCOEFF_ATT" = "" ] ; then DEF_COEFF_ATT="0" ; fi

    case $CHANNELS in
	2)
	    sed -i -- s/"to_outputs:\"left\"\/0\/0;"/"to_outputs:\"left\"\/"$DEF_COEFF_ATT"\/"$DEF_COEFF_PHASE";"/g /root/brutefir_config
	    sed -i -- s/"to_outputs:\"right\"\/0\/0;"/"to_outputs:\"right\"\/"$DEF_COEFF_ATT"\/"$DEF_COEFF_PHASE";"/g /root/brutefir_config

	    sed -i -- s/"coeff:\"left0\";"/"coeff:\"left"$DEF_COEFF"\";"/g /root/brutefir_config
	    sed -i -- s/"coeff:\"right0\";"/"coeff:\"right"$DEF_COEFF"\";"/g /root/brutefir_config
	    ;;

	4)
	    sed -i -- s/"to_outputs:\"left\"\/0\/0;"/"to_outputs:\"left\"\/"$DEF_COEFF_ATT"\/"$DEF_COEFF_PHASE";"/g /root/brutefir_config
	    sed -i -- s/"to_outputs:\"right\"\/0\/0;"/"to_outputs:\"right\"\/"$DEF_COEFF_ATT"\/"$DEF_COEFF_PHASE";"/g /root/brutefir_config
	    sed -i -- s/"to_outputs:\"sleft\"\/0\/0;"/"to_outputs:\"sleft\"\/"$DEF_COEFF_ATT"\/"$DEF_COEFF_PHASE";"/g /root/brutefir_config
	    sed -i -- s/"to_outputs:\"sright\"\/0\/0;"/"to_outputs:\"sright\"\/"$DEF_COEFF_ATT"\/"$DEF_COEFF_PHASE";"/g /root/brutefir_config

	    sed -i -- s/"coeff:\"left0\";"/"coeff:\"left"$DEF_COEFF"\";"/g /root/brutefir_config
	    sed -i -- s/"coeff:\"right0\";"/"coeff:\"right"$DEF_COEFF"\";"/g /root/brutefir_config
	    sed -i -- s/"coeff:\"sleft0\";"/"coeff:\"sleft"$DEF_COEFF"\";"/g /root/brutefir_config
	    sed -i -- s/"coeff:\"sright0\";"/"coeff:\"sright"$DEF_COEFF"\";"/g /root/brutefir_config
	    ;;
    esac
}



start() {
    printf "Preparing BruteFIR config: "
    prepare_config
    echo "OK"
    printf "Starting $DAEMON_NAME: "
    if start-stop-daemon --make-pidfile -p$PIDFILE --start --quiet --background \
			  --startas /bin/sh \
			  -- -c "exec $DAEMON $DAEMON_ARGS >/var/log/brutefir.log 2>&1"
    then
	until echo 'lf' | nc localhost 3000 &> /dev/null; do sleep 0.1 ; done
	echo "OK"
    else
	echo "FAIL"
	exit -1
    fi

}

stop() {
        printf "Stopping $DAEMON_NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?
