#!/bin/sh

touch /var/log/squeezelitelog.txt

tail -fn0 /var/log/squeezelitelog.txt | \
while read line ; do
	echo "$line" | grep -q "slimproto:848"
	if [ $? = 0 ]
	then
		#echo "CheckLMS: Treffer"
		LMSADDR=$(echo "$line" | grep slimproto | grep connecting| awk -F'[: ]' '{print $8}')
		if [ "$LMSADDR" = "127.0.0.1" -o "LMSADDR" = "localhost" ]
		then
			#echo "CheckLMS: is localhost"
			ETHADDR=$(ifconfig | grep -A 2 eth0 | grep -w inet -m1 | grep -v 127 | awk -F[:] '{ print $2  }' | awk -F[:' '] '{ print $1 }')
			if [ "$ETHADDR" = "" ]
			then
				sleep 10
				WLANADDR=$(ifconfig | grep -A 2 wlan0 | grep -w inet -m1 | grep -v 127 | awk -F[:] '{ print $2  }' | awk -F[:' '] '{ print $1 }')
				LMSADDR=$WLANADDR
			else	
				LMSADDR=$ETHADDR
			fi
		fi
		echo "CheckLMS:    Our LMS-server-address is: $LMSADDR"
		echo "$LMSADDR" > /var/log/lmsaddress
	fi
done
