#!/bin/sh

. /etc/aroio/userconfig

. /opt/shutils.sh

NAME=gmediarender
USER=gmediarender
GROUP=gmediarender
DAEMON=/usr/bin/gmediarender
PIDFILE=/var/run/$NAME.pid

MACADDR=$(macaddr)

DAEMON_ARGS="-u \"$MACADDR\" -f \"$PLAYERNAME\" "
if [ "$BRUTEFIR" = "OFF" ]
then
    DAEMON_ARGS="$DAEMON_ARGS --gstout-audiosink=alsasink"
    if [ "$MSCODING" = "ON" ]
    then
	DAEMON_ARGS="$DAEMON_ARGS --gstout-audiodevice=mscoded"
    else
	DAEMON_ARGS="$DAEMON_ARGS --gstout-audiodevice=stereo"
    fi
else
    DAEMON_ARGS="$DAEMON_ARGS --gstout-audiosink=jackaudiosink --gstout-audiostringproperties=port-pattern=brutefir"
fi

start() {
    printf "Starting $NAME: "
    start-stop-daemon -c $USER:$GROUP --make-pidfile -p$PIDFILE --start --quiet --background --exec "$DAEMON" \
                      -- $DAEMON_ARGS \
        && echo "OK" || echo "FAIL"
    clogn "$(dirname $DAEMON) cmdline: $DAEMON $DAEMON_ARGS"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
	status)
	    check_status "$DAEMON" "$PIDFILE" && exit 0 || exit 1
	    ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
