#!/bin/sh

NAME=httpd
DAEMON=/usr/sbin/httpd
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS="-h /opt/www -c /etc/httpd.conf"

. /etc/aroio/userconfig

start() {
    printf "Starting $NAME: "
    echo -e '*.php:/usr/bin/php-cgi\n/:aroio:'"$USERPASSWD" > /etc/httpd.conf
    start-stop-daemon --make-pidfile -p$PIDFILE --start --quiet --background --exec "$DAEMON" \
                      -- $DAEMON_ARGS \
        && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
