#!/bin/sh

. /etc/aroio/userconfig

. /opt/shutils.sh

NAME=jackd
DAEMON=/usr/bin/jackd
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS="-ddummy -r96000 -p 1024"
JACKBUFFER=1024

#if [ "$SOUNDCARD" = "M-Audio Fast Track Pro" ] && [ "$CHANNELS" = "4" ]
#then	DAEMON_ARGS="-R -P 10 -dalsa -P -dftp4ch -r"$RATE"000 -p $JACKBUFFER -n2"
#else	DAEMON_ARGS="-R -P 10 -dalsa -i 2 -o "$CHANNELS" -P -dhw:0 -r"$RATE"000 -p $JACKBUFFER -n2"
#fi

# Always use a jackd multplier ( -n ) of 3 to be compatible with USB-Interfaces!

case $SOUNDCARD in
	"M-Audio Fast Track Pro")
	if [ "$CHANNELS" = "4" ] ; then DAEMON_ARGS="-R -P 10 -dalsa -P -dftp4ch -r"$RATE"000 -p $JACKBUFFER -n3" ; fi
	;;

	"RME Fireface UCX")
	JACKBUFFER=1024
	DAEMON_ARGS="-R -P 10 -dalsa -i 2 -o "$CHANNELS" -P -dhw:0 -r"$RATE"000 -p $JACKBUFFER -n3"
	;;

	"Focusrite Scarlett")
	JACKBUFFER=1024
	DAEMON_ARGS="-R -P 10 -dalsa -C -P -dhw:0 -r"$RATE"000 -p $JACKBUFFER -n3"
	;;

	*)
	JACKBUFFER=8192
	DAEMON_ARGS="-R -P 10 -dalsa -P -dhw:0 -r"$RATE"000 -p $JACKBUFFER -n3"
	;;
esac


start() {
    cmark
    clog -n "Starting $NAME: "
    # Start jackd via /bin/bash to allow proper redirection of stdout to a log file
    if start-stop-daemon --make-pidfile -p$PIDFILE --start --quiet --background \
			 --startas /bin/sh \
			 -- -c "exec $DAEMON $DAEMON_ARGS >/var/log/jackd.log 2>&1"
    then
	jack_wait -w -t 5
	if [ $(jack_wait -c) = "running" ]
	then clog "OK"
	else clog "FAIL"
	fi
	if [ "$AUDIOPLAYER" = "netjack"  ]
	then
	    clog -n "Loading jack netmanager: "
	    if [ "$(cat /sys/class/net/eth0/carrier)" = "1" ]
	    then
		jack_load netmanager >> /var/log/jackd.log \
		    && clog "OK" || clog "FAIL"
		/etc/init.d/brutefir_connect_netjackports &> /dev/null &
	    else
		clog "No network carrier found, cannot start netjack!" >> /var/log/jackd.log
		clog "No network carrier, not starting"
	    fi
	fi
    else
	clog "FAIL"
    fi
    clogn "Jack cmdline: exec $DAEMON $DAEMON_ARGS"
}

stop() {
        clog -n "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && clog "OK" || clog "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                clog "Usage: $0 {start|stop|restart}"
                exit 1
esac
