#!/bin/sh
. /mnt/mmcblk0p1/userconfig.txt

## unklar, aber dabei
modprobe bcm2835-gpiomem
modprobe uio
modprobe uio_pdrv_genirq
#modprobe ehci-hcd

## WIFI
  modprobe 8192cu
  modprobe 8812au

## AUDIO
#  modprobe bcm2708-dmaengine
#  modprobe i2c-bcm2708
#  modprobe snd-soc-bcm2708-i2s
#  modprobe snd-soc-pcm512x
#  modprobe snd-soc-pcm512x-i2c

## DAC erkennen
case $SOUNDCARD in
'IQAudIO DAC')
	modprobe snd-soc-iqaudio-dac
	;;

'HiFiBerry Digi')
	modprobe regmap-spi
	modprobe snd-soc-wm8804
	modprobe snd-soc-wm8804-i2c
	modprobe snd-soc-hifiberry-digi
	;;

'HiFiBerry DAC+')
#	modprobe snd-soc-pcm5102a
#	modprobe snd-soc-bcm2708
	modprobe snd-soc-pcm512x
	modprobe snd-soc-pcm512x-i2c
	modprobe regmap-spi
	modprobe regmap-i2c
	snd-soc-bcm2708-i2s
	modprobe snd-soc-wm8804
	modprobe snd-soc-wm8804-i2c
	modprobe clk-hifiberry-dacpro
	modprobe snd-soc-hifiberry-dac
	modprobe snd-soc-hifiberry-dacplus
	;;

'M-Audio Fast Track Pro')
	modprobe snd_usb_audio vid=0x763 pid=0x2012 device_setup=0x09 index=0 enable=1
	;;
'Focusrite Scarlett')
	modprobe snd_usb_audio
	;;

'NI Audio 8 DJ')
	modprobe snd_timer
	modprobe snd_pcm
	modprobe snd_usb_caiaq
	;;

esac
## Bluetooth
#  modprobe btusb
