#!/bin/sh

. /etc/aroio/userconfig
. /opt/shutils.sh

NAME=shairport-sync
PIDFILE=/var/run/$NAME.pid

start() {
    ETHADDR=$(ethaddr)
    WLANADDR=$(wlanaddr)
    until ! [ "$ETHADDR" = "" ] || ! [ "$WLANADDR" = "" ]
    do
	echo "Shairport:   Network not available, waiting..."
	sleep 2
	ETHADDR=$(ethaddr)
	WLANADDR=$(wlanaddr)
    done
    if [ "$DEBUG" = "ON" ] ; then
	touch /var/log/shairportlog.txt
    fi

    if [ "$BRUTEFIR" = "OFF" ] ; then
	PLAYER="shairport-sync"
	if [ "$MSCODING" = "ON" ] ; then
	    OUTPUT=" -o alsa -- -d mscoded"
	else 	OUTPUT=" -o alsa -- -d stereo"
	fi
    else
	PLAYER="shairport-sync"
	OUTPUT=" -o jack -- brutefir"
    fi

    DAEMON=/usr/bin/$PLAYER

    DAEMON_ARGS="-d -m avahi -v -w -B /opt/aroio/shairport-sync-startaction -E /opt/aroio/shairport-sync-stopaction \
	-a "$PLAYERNAME" $OUTPUT "
    printf "Starting $NAME: "
    clogn "$(basename $DAEMON) cmdline: $DAEMON $DAEMON_ARGS"
    start-stop-daemon --start --quiet --exec "$DAEMON" \
                -- $DAEMON_ARGS \
        && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
