#!/bin/sh

. /etc/aroio/userconfig

. /opt/shutils.sh

NAME=squeezelite
USER=squeezelite
GROUP=squeezelite
DAEMON=/usr/bin/squeezelite
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS="-z -P $PIDFILE -f /var/log/squeezelitelog.txt"

start() {
    if ! [ "$SERVERNAME" = ""  ]
    then
	if ! (ping -c1 $SERVERNAME) &> /dev/null
	then
	    #echo "Squeezelite: Squeezebox-Server "$SERVERNAME" not available, waiting..."
	    until (ping -c1 $SERVERNAME) &> /dev/null
	    do
		sleep 0.2
	    done
	fi
    else
	until (ping -c1 127.0.0.1) &> /dev/null
	do
	    sleep 0.3
	done
	echo "Squeezelite: Network available!"
    fi

    sleep 1
    if grep 1 /sys/class/net/eth0/carrier &> /dev/null
    then	MACADDR=$(cat /sys/class/net/eth0/address)
    else	MACADDR=$(cat /sys/class/net/wlan0/address)
    fi

    if ! [ "$SERVERNAME" = "" ]
    then
	echo -e "Squeezelite: LMS-Server available, starting up..."
	SERVEROPT="-s $SERVERNAME"
    else
	echo "Squeezelite: LMS-Server set to be automagically detected, starting up."
	SERVEROPT=""
    fi
    if [ "$DEBUG" = "ON" ]
    then
	echo "             Debugging activated in userconfig.txt, logging to /var/log/"
	DEBUGSQUEEZE="-d all=info -f /var/log/squeezelitelog.txt"
    else
	DEBUG=""
    fi
    ALSAPARAMS="-a 8192:1024:32:0 -b 1024:8192"
    if [ "$MSCODING" = "ON" ]
    then
	OUTPUT="-o mscoded"
	echo "             Output is MS-coded!"
    else
	OUTPUT="-o plughw:0,0"
	echo "             Output is stereo!"
    fi
    DAEMON_ARGS="$DAEMON_ARGS -m $MACADDR -n $PLAYERNAME $SERVEROPT $OUTPUT $DEBUGSQUEEZE $ALSAPARAMS"

    printf "Starting $NAME: "
    start-stop-daemon --start --quiet --exec "$DAEMON" \
                      -- $DAEMON_ARGS \
        && echo "OK" || echo "FAIL"
    clogn "$(basename $DAEMON) cmdline: $DAEMON $DAEMON_ARGS"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
	status)
	    check_status "$DAEMON" "$PIDFILE" && exit 0 || exit 1
	    ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
