#!/bin/sh

. /etc/aroio/userconfig

. /opt/shutils.sh

NAME=squeezelite-jack
DAEMON=/usr/bin/squeezelite-jack
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS="-o jack -M AroioEX -a brutefir -z"

start() {
    cmark
    clog -n "Starting $NAME: "

    if [ "$MSCODING" = "ON" ]
    then	clog -n " (ms-coded!) "
    else	clog -n " (stereo!) "
    fi
    RATE="-r 96000-96000 "
    RESAMPLE="-R -u hL"
    ALSAPARAMS="-b 1024:16384"

    DAEMON_ARGS="$DAEMON_ARGS -n $PLAYERNAME -z $RATE $RESAMPLE $ALSAPARAMS"

    start-stop-daemon --make-pidfile -p$PIDFILE --start --quiet --exec "$DAEMON" \
                      -- $DAEMON_ARGS \
        && clog "OK" || clog "FAIL"
    clogn "squeezelite-jack cmdline: $DAEMON $DAEMON_ARGS"
}

stop() {
    clog -n "Stopping $NAME: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE \
        && clog "OK" || clog "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                clog "Usage: $0 {start|stop|restart}"
                exit 1
esac
