#!/bin/sh
# return Volume
#echo 'lf' | nc localhost 3000 | awk -F: '/to outputs:[[:space:]]*0\/(-?[[:digit:]]*\.[[:digit:]]*)/ {print $2}'
echo 'lf' | nc 127.0.0.1 3000 | awk -F: '/from inputs:[[:space:]]*0\/(-?[[:digit:]]*\.[[:digit:]]*)/ {print $2}'
