#!/bin/sh

#/etc/init.d/checkstatus >> /dev/null 2>&1 &
# Screen Blanking abschalten
echo -e "\033[9;0]"

LD_LIBRARY_PATH=/lib
export LD_LIBRARY_PATH
TZ="Europe/Berlin"
export TZ

. /opt/shutils.sh

mount -t sysfs sysfs /sys

mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mount -o ro /dev/mmcblk0p1 /mnt/mmcblk0p1

echo "aroio Version: $(cat /VERSION)"

# If there is a userconfig: copy it
if [ -e /mnt/mmcblk0p1/userconfig.txt ]; then
    cp /mnt/mmcblk0p1/userconfig.txt /etc/aroio/userconfig
fi

/etc/init.d/checksoundcard | tee -a /tmp/shell.log

/etc/init.d/gpio &
/etc/init.d/checkstatus &> /dev/null &

#/etc/init.d/checkuserconfig

mount none -t tmpfs -o defaults /var
mount none -t tmpfs -o defaults /tmp
mount none -t tmpfs -o defaults /home/sftparoio

mkdir /dev/shm
mount none -t tmpfs -o defaults /dev/shm

mkdir -p /var/run/dbus

(/etc/init.d/network | tee -a /tmp/shell.log)&

export LANG=en_US.utf8
mkdir /var/log

/etc/init.d/amixer | tee -a /tmp/shell.log &
clog "System:      Copying default filters..."
cp -ar /mnt/mmcblk0p1/brutefir/*.dbl /home/sftparoio
gunzip -c /mnt/mmcblk0p1/filter.tgz | tar xf - -C /home/sftparoio | tee -a /tmp/shell.log && mv /home/sftparoio/filter/* /home/sftparoio && rmdir /home/sftparoio/filter
chown -R sftparoio /home/sftparoio

#/etc/init.d/checkfilters &
touch /var/log/shairportlog.txt

chmod 777 /dev/null && dropbear  | tee -a /tmp/shell.log

(
    logstart /etc/init.d/modules
    logstart /etc/init.d/avahi-setup start
    logstart /etc/init.d/dbus start
    logstart /etc/init.d/avahi-daemon start
    logstart /etc/init.d/audio start
)&

logstart /etc/init.d/httpd start


loadkmap < /etc/de.map
/opt/aroio/syncconfig.sh &
/etc/init.d/logrotate &> /dev/null &
/etc/init.d/ntpd &> /dev/null &

exit 0
